### ISSUE TITLE
Not_found_fix problem

### ISSUE THREAD

**Issue by NeaPopa** [inigoflores/pisces-p100-tools#4]
Hi there. 
I applied the not found fix. Everything went well for a few days. 
I changed the location of the miner, so i had it offline for 5 hours or so. 
Ever since then the peer book list is decreasing constantly! Yesterday had 130-120k; now it's 60k & still going down.
I restored the original version of sys.config, then applied the fix again. To no good apparently.
Any suggestions?

**Comment by inigoflores** [comment]
Hi

Due to its size, currently the P2P network is very unstable and a large proportion of miners are struggling in maintaining a healthy peer book. Your miner is trying to fetch peer book data from other miners which are also experiencing issues. So, I'm afraid,  there's not much we can do other than wait two weeks for HIP55 to be activated, and hope that the network readjusts on its own during this time. Sorry for not being able to help further.

I'm closing this for now.

Kind regards
